// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFuMO4izU3RWZzBd0BOEoerGE_YOF5YWQ',
    appId: '1:1074794759969:web:9b6bdaac2f2c1e2aaa2060',
    messagingSenderId: '1074794759969',
    projectId: 'how-about-here-181dc',
    authDomain: 'how-about-here-181dc.firebaseapp.com',
    storageBucket: 'how-about-here-181dc.appspot.com',
    measurementId: 'G-1GZMX1XRJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYqm5sCwGZWVUWaqhoDp081FkvxsZEvU8',
    appId: '1:1074794759969:android:083319b2cee596dbaa2060',
    messagingSenderId: '1074794759969',
    projectId: 'how-about-here-181dc',
    storageBucket: 'how-about-here-181dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7HeRiO_cgYkytIoQ3aa5OXxDmKlTsDk',
    appId: '1:1074794759969:ios:deccf30b0104df86aa2060',
    messagingSenderId: '1074794759969',
    projectId: 'how-about-here-181dc',
    storageBucket: 'how-about-here-181dc.appspot.com',
    iosBundleId: 'com.example.hah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl7HeRiO_cgYkytIoQ3aa5OXxDmKlTsDk',
    appId: '1:1074794759969:ios:deccf30b0104df86aa2060',
    messagingSenderId: '1074794759969',
    projectId: 'how-about-here-181dc',
    storageBucket: 'how-about-here-181dc.appspot.com',
    iosBundleId: 'com.example.hah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFuMO4izU3RWZzBd0BOEoerGE_YOF5YWQ',
    appId: '1:1074794759969:web:28d0eb75e6de5aefaa2060',
    messagingSenderId: '1074794759969',
    projectId: 'how-about-here-181dc',
    authDomain: 'how-about-here-181dc.firebaseapp.com',
    storageBucket: 'how-about-here-181dc.appspot.com',
    measurementId: 'G-23KPQHQBKT',
  );
}
